In [7]:
#program 1
#create a numpy array of 10 int and display shape,size,data type
b=np.array([1,2,3,4,5,6,7,8,9,10])
print(b.shape)
print(b.size)
print(b.dtype)
print(b.ndim)

(10,)
10
int64
1


In [11]:
#program 2
#create a 3x3 matrix and access 1st element,last,element,entire 2nd row
import numpy as np
a = np.arange(1, 10).reshape(3, 3)
print(a)
first_element = a[0, 0]
last_element = a[-1, -1]
second_row = a[1, :]
print("\nFirst element:", first_element)
print("Last element:", last_element)
print("Entire 2nd row:", second_row)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

First element: 1
Last element: 9
Entire 2nd row: [4 5 6]


In [16]:
#program 3
#create an array from 1 to 20 and display 1st 10 elements,last 5 elements,alternate elements
arr=np.arange(1,21)
print(arr)
print(arr[:10])
print(arr[-5:])
print(arr[::2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10]
[16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]


In [19]:
#program 4
#create an array of 12 elemnts and reshape it int 3x4,2x6
c=np.arange(1,13)
print(c)
new_c=c.reshape(3,4)
print(new_c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
new_c=c.reshape(2,6)
print(new_c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [21]:
#program5
#perform addition,subtraction,multiplication and division of two arrays
a=np.array([2,34,67,22,71,85])
b=np.array([122,32,57,49,67,99])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[124  66 124  71 138 184]
[-120    2   10  -27    4  -14]
[ 244 1088 3819 1078 4757 8415]
[0.01639344 1.0625     1.1754386  0.44897959 1.05970149 0.85858586]
