In [1]:
import numpy as np


In [3]:
a=np.array([1,2,3,4,])
print(a)

[1 2 3 4]


In [4]:
b=np.array([ [1,2,3,4],[5,6,7,8] ])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
import numpy as np
c=np.array([ [[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]] ])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [3]:
import numpy as np
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [1]:
import numpy as np
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [1]:
import numpy as np
arr=np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [1]:
import numpy as np
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [5]:
b=np.array([ [1,2,3,4],[5,6,7,8] ])
print(b.shape)
print(b.ndim)
print(b.dtype)
print(b.size)

(2, 4)
2
int64
8


In [6]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[3])
print(arr[-1])

10
40
50


In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


In [8]:
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])

[20 30 40]


In [9]:
print(arr[:3])

[10 20 30]


In [10]:
print(arr[3:])

[40 50 60]


In [11]:
print(arr[::2])

[10 30 50]


In [14]:
#slicing 2 d arrays
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [15]:
arr=np.arange(1,13)
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
arr=np.arange(1,13)
new_arr=arr.reshape(2,3,2)
print(new_arr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
arr=np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(b+a)

[5 7 9]
[5 7 9]


In [3]:
print(a-b)
print(b-a)

[-3 -3 -3]
[3 3 3]


In [4]:
print(a*b)

[ 4 10 18]


In [5]:
print(a/b)

[0.25 0.4  0.5 ]


In [6]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


In [11]:
arr=np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

150
30.0
50
10
14.142135623730951
